import Head from 'next/head'
import { ReactNode } from 'react'
import { RainbowKitProvider } from '@rainbow-me/rainbowkit'
import Layout from '@/layout'
import { MountsProvider, WagmiConfigProvider } from '@/components'
import { config } from '@/config'
import { useMounted } from '@/hooks'

import '@/styles/globals.css'
import '@rainbow-me/rainbowkit/styles.css'

export default function App({ Component, pageProps }: any) {
  const layout = Component.layout || defaultLayout
  const mounted = useMounted()

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <MountsProvider
        install={[
          { component: WagmiConfigProvider, props: { config } },
          { component: RainbowKitProvider },
        ]}
      >
        {mounted && layout(<Component {...pageProps} />)}
      </MountsProvider>
    </>
  )
}

function defaultLayout(page: ReactNode) {
  return <Layout>{page}</Layout>
}
